# distance (in blocks) from the bank within which the player is considered a game participant
# (shows up in the scoreboard, is allowed to use chat entries, receives game messages)
# note: they are considered such anyway if they have a game item in their inventory
game-distance: 16

# item ids to be used as game items
items:
    # both items and denominations can be specified
    money:
        1: minecraft:flint
        5: minecraft:coal
        10: minecraft:quartz
        20: minecraft:lapis_lazuli
        50: minecraft:iron_nugget
        100: minecraft:gold_nugget
        500: minecraft:emerald
        # example of custom amount-item pair:
        # 4269: minecraft:wet_sponge
    chance: minecraft:chorus_fruit
    community-chest: minecraft:diamond

# game scoreboard settings
scoreboard:
    # whether to use the name that is shown in tab-menu (this may include colors, group prefixes, etc.)
    # plain player nickname is used by default
    use-display-name: false
    # old-new pairs to perform replacement before displaying player names as a game scoreboard entry
    # (supports regular expressions, most likely color-code-sensitive)
    name-replace-map: # type: list of nodes with two keys: "old" and "new"
        # example: remove prefix in square brackets
        # - old: '^\[\w+\] '
        #   new: ''
    # player names (exact) to not be transformed by replacements
    name-replace-map-exclusions: # type: list of strings
        # example:
        # - KruASe
        # - KruASe_2

# plugin messages, can be used to add translation
messages:
    # to turn off certain info messages leave the field empty (not empty quotes!)
    info:
        game-start: '{player} started a game at {coordinates} in the {dimension}!'
        game-finish: '{player} finished the game'
        game-force-finish: '{player} §cforce§r-finished the game'
        add-money: '{player} added {n} to the bank'
        add-item: '{player} added {item}'
        remove-money: '{player} removed {n} from the bank'
        remove-item: '{player} removed {item}'
        houses-left: '{n} houses left in the bank!'
        hotels-left: '{n} hotels left in the bank!'
        dice: 'Dice: {a} {b}'
    error:
        no-permission: Not enough permissions to call this command!
        invalid-command: Invalid command!
        player-only: This command can only be called by a player!
        game-not-started: Game is not started!
        game-already-started: Game is already started on this server!
        not-a-container: The bank block has to be a chest, barrel, or any type of shulker box!
        standing-on-chest: When you are standing on a chest, Minecraft thinks you are inside instead ¯\_(ツ)_/¯
        unable-to-finish-game: 'Unable to finish the game: not all game items have been returned! To force-finish call §a/mn finish forced'
        unable-to-add-item: Unable to add item to the inventory!
        too-much-money: Man, this exceeds java integer value limit, I'm sure you don't need so much...
        not-enough-money: The bank contains less money than it is requested to remove!
        property-already-in-game: This property is already in game!
        no-houses-left: There are no more houses left! (Maximum of 32)
        no-hotels-left: There are no more hotels left! (Maximum of 12)
    # not intended to be edited
    # when adding translation, please carefully keep formatting (if you are unsure how it works)
    help:
        header: §7-------- §6[§aMineNopoly§6] §7------------------------
        help: §a/mn §6help §a[command] §r- Show help for given command, for available commands otherwise
        start: §a/mn §6start §a<block> §r- Start the game with given block as the bank
        finish: §a/mn §6finish §r- Finish the game and save the log file
        finish-forced: §a/mn §6finish forced §r- Finish even if not all game items have been returned
        book: §a/mn §6book §r- Get the book to use during the game
        reload: §a/mn §6reload §r- Reload config
        get: §a/mn §6get §a<args> §r- Auxiliary command used when clicking on links in the book
